ALTER VIEW dbo.C_ACCOUNTS AS
SELECT A.*, 
	AT.DESCRIP + ' ' + ISNULL(AST.DESCRIP,'') AS ACC_DESCRIP,
	DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME,
	CA1.ATTRIB_VALUE AS IS_CONTROL_COMMENT
FROM dbo.ACC_VIEW A (NOLOCK)
	LEFT JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = A.DEPT_NO
	LEFT JOIN dbo.ACC_TYPES AT (NOLOCK) ON AT.ACC_TYPE = A.ACC_TYPE
	LEFT JOIN dbo.ACC_SUBTYPES AST (NOLOCK) ON AST.ACC_TYPE = A.ACC_TYPE AND AST.ACC_SUBTYPE = A.ACC_SUBTYPE
	LEFT JOIN dbo.ACC_ATTRIBUTES CA1 (NOLOCK) ON CA1.ACC_ID = A.ACC_ID AND CA1.ATTRIB_CODE = '$IS_CONTROL_COMMENT'
GO
